### ISSUE TITLE
問題ファイルでビア位置のZ座標が降順の場合エラーになる

### ISSUE THREAD

**Issue by kotarot** [dasadc/conmgr#14]
早稲田大学の寺田です。お世話になっています。

問題ファイルでビア位置の指定で、Z座標を降順で記述するとチェック (`server/nlcheck.py`) が通りません。ビア層の記述順番に関してはルール仕様として定義されていないと思いますが、仕様として捉えてしまって良いでしょうか？

具体例としてビア記述の部分が

```
VIA#b (2,0,1) (2,0,2)
```

だとチェックが通るもので、代わりに

```
VIA#b (2,0,2) (2,0,1)
```

とするとエラーとなります。

**Comment by shibasay** [comment]
DAS２０１６幹事 柴田です。

ご指摘ありがとうございます。バグでした。
ビア位置指定の順番に制限はございません。
下記にてコミットにて修正しました。ご確認いただければ幸いです。
540fe0a9d8c37cc776c7db0602742b38b535fd1e

**Comment by kotarot** [comment]
早稲田大学戸川研究室の寺田です。動作確認致しました。修正ありがとうございます。
