### ISSUE TITLE
自作問題に関する質問

### ISSUE THREAD

**Issue by kotarot** [dasadc/conmgr#17]
早稲田大学の寺田です。大変お世話になっております。
コンテスト直前で恐縮ですが、自作問題に関していくつか質問させてください。
1. 提出できる自作問題の個数は昨年と同じく各チーム最大3問でしょうか？
2. ドキュメントを読む限り盤面サイズの上限が（層数以外）定まっていないように思われますが、XとYの上限はいくらでしょうか？
3. 同じくラインの数の上限はいくらでしょうか？
4. ビア個数の上限値はa~zとaa~zzの702個という認識で正しいでしょうか？

以上、ご回答いただければ幸いです。よろしくお願い致します。

**Comment by shibasay** [comment]
DAS2016幹事 柴田です。回答します。ルール定義が明確で無く申し訳ありません。READMEにも記載します。
1. はい、3問です。
2. 盤面サイズは 36x36 が最大です。
3. ライン数に上限は設定しておりません。
4. ビア個数に上限は設定しておりません。

**Comment by kotarot** [comment]
寺田です。回答いただきありがとうございます。
