### ISSUE TITLE
nlcheck.py - 迂回の多い正解を不正解と判定してしまう?

### ISSUE THREAD

**Issue by takijuso** [dasadc/conmgr#18]
## 問題

コの字型の迂回が連続するような回答をnlcheck.pyに提出すると、
正解パスが存在すると思われるにも関わらず、不正解と判定されることがあります。
例えば、以下のような問題と回答の組の場合などです。
[NL_Q01M.txt](https://github.com/dasadc/conmgr/files/473797/NL_Q01M.txt)

[NL_Q01MA.txt](https://github.com/dasadc/conmgr/files/473796/NL_Q01MA.txt)

チームADC-5のソルバではコの字型を解消する整形を最後に行うように改良したところ、症状が発生しなくなりました。
直前の報告で申し訳ないですが、調査をお願いいたします。

**Comment by shibasay** [comment]
DAS2016幹事 柴田です。

本件、提出頂いた回答のLINE#6の件ととらえました。
これは4つの数字6が隣り合った状態になっています。
本コンテストでは、隣り合う２つのマスが同じ場合、結線されていると判定します。
よって隣り合う４つの数字はそれぞれ結線されていると判定され、
「線が分岐している」と見なされます。これにより nlcheck.py ではErrorと見なされます。

**Comment by ysnt27** [comment]
同じくアルゴリズムデザインコンテスト担当の富田です。
補足します。
NL_Q01MA.txt の場合、下記リンク先の画像のように線が引かれている、と解釈されます。
https://drive.google.com/open?id=0BwIiA7yZwFtiM255UzBGbXN5Y2M
https://drive.google.com/open?id=0BwIiA7yZwFtiUHFVeFVsY0N0UlE

そのため線が分岐している、というわけです。

**Comment by ysnt27** [comment]
同じくアルゴリズムデザインコンテスト担当の富田です。
補足します。
NL_Q01MA.txt の場合、下記リンク先の画像のように線が引かれている、と解釈されます。

![nl_q01ma 1](https://cloud.githubusercontent.com/assets/11625718/18537909/b1963ce8-7b43-11e6-9840-b916994b16a4.gif)
![nl_q01ma 0](https://cloud.githubusercontent.com/assets/11625718/18537910/b1972284-7b43-11e6-9146-4edbdb1ebd37.gif)

そのため線が分岐している、というわけです。

**Comment by takijuso** [comment]
なるほど、承知しました。
確か2015年度のADCで、我々のソルバで許容解となったが不正解と判定された問題があると記憶しており、
もしかしたらこの解釈の問題に引っかかったものかもしれないです。
一応、パスとパスが隣接するような解は不正解になるという反例のようなものを記載していただき、
開発者に、冗長な経路を取り除くことを確実に要求して頂いたほうがよろしいかと思います。
（解の品質というインセンティブがあるとはいえ…。）
来年以降の運営の参考にしていただければ幸いです。
