### ISSUE TITLE
ファイルの改行コード

### ISSUE THREAD

**Issue by ysnt27** [dasadc/conmgr#3]
CR LFでいいのか？

**Comment by ysnt27** [comment]
歴史的事情で、CR+LFのMS-DOS形式となっています。
公式ドキュメントにも、そういう記載があります。
実際には、この自動運営システムでは、CR+LF、LFのみ、CRのみ、どれでも受け取れるように作ったつもりですが、テストしてません。危ない気がしています。

**Comment by ysnt27** [comment]
簡単なテストをしてありますが、自動運営システム側では、CR LF（MS-DOS）、LFのみ（Unix）、CRのみ（Mac）、３形式とも読めるようになっていると思います。

改行コードではなくて、別の話です。
UnicodeのときのBOM(byte order mark)がついていると、正しく読み取れない、ということが、コンテスト当日に判明しました。
Unicodeを使うときは、BOM無しにしてください。というか、ASCIIのテキストファイル形式にしてください。

**Comment by ysnt27** [comment]
server/nlcheck.py では、BOMを削除する処理を追加済みです。

**Comment by shibasay** [comment]
CLIから呼び出した場合と、WebUIから呼び出した場合とで挙動が異なったため、
以下コミットにてUTF-8 BOM の処理方式を変更しました。
（BOMを明示的に削除する方式から、再unicode化時にエンコードを 'utf-8-sig' と指定する方式に変更）
fe055b94d7d0825dbd2244832cb28cc8d48ae90d
呼び出し方にかかわらず、UTF-8も正常に扱えるようになったはずです。
